server:
  retention: "3d"

  service:
    type: ClusterIP

  persistentVolume:
    enabled: true
    storageClass: gp3
    size: 8Gi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

alertmanager:
  enabled: true

  persistence:
    enabled: true
    storageClass: gp3
    size: 2Gi

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: true
