controller:
  admin:
    username: admin
  containerEnvFrom:
    - secretRef:
        name: jenkins-github-token

  serviceType: ClusterIP
  servicePort: 8080
  targetPort: 8080

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  additionalPlugins:
    - credentials-binding:latest
    - github:latest
    - job-dsl:latest
    - authorize-project:latest

  JCasC:
    configScripts:
      build-authorization: |
        security:
          queueItemAuthenticator:
            authenticators:
              - global:
                  strategy: triggeringUsersAuthorizationStrategy
      seed-job: |
        jobs:
          - script: |
              job('seed-job') {
                description('Job to generate pipeline for Django project')

                scm {
                  git {
                    remote {
                      url('https://github.com/ayri77/neoversity-devops-ci-cd-lab.git')
                    }
                    branches('*/final-project')
                  }
                }

                steps {
                  dsl {
                    text('''
                      pipelineJob('final-project-django-docker') {
                        description('Build and push the Django image to Amazon ECR')

                        definition {
                          cpsScm {
                            scm {
                              git {
                                remote {
                                  url('https://github.com/ayri77/neoversity-devops-ci-cd-lab.git')
                                }
                                branches('*/final-project')
                              }
                            }

                            scriptPath('Jenkinsfile')
                          }
                        }
                      }
                    ''')
                  }
                }

                configure { project ->
                  def dslStep = project.builders[0].'javaposse.jobdsl.plugin.ExecuteDslScripts'[0]
                  dslStep.appendNode('sandbox', true)
                }
              }
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github-token
                      username: ayri77
                      password: "${GITHUB_TOKEN}"
                      description: GitHub PAT for GitOps repository
persistence:
  enabled: true
  storageClass: "gp3"
  size: "10Gi"

agent:
  serviceAccount: jenkins-sa
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

serviceAccountAgent:
  create: false
  name: jenkins-sa