{{- range .Values.repositories }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ .name }}-repository
  namespace: {{ $.Release.Namespace }}

  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: {{ .type | default "git" | quote }}
  url: {{ .url | quote }}
  insecure: {{ $.Values.repoConfig.insecure | quote }}
  enableLfs: {{ $.Values.repoConfig.enableLfs | quote }}
{{- end }}